### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by andreybolonin**
what about to enable this repo on Travis?

### CODE REVIEW

**Comment by areski** [comment]
I doubt A2Billing will work with PHP7, have you tried?

**Comment by andreybolonin** [comment]
No, but Travis is very good feature for open source project.
And, if we have some errors with php7.x - we can fix them.

Can you enable travis for this repo?

**Comment by areski** [comment]
Yes I have been using Travis-ci on tons of projects but A2Billing is an old code base (started in 2004) with almost unexisting tests, so prior to enable travis, we should make sensible progress on building a test suit.
Please reopen this PR when you have done added some tests

**Comment by andreybolonin** [comment]
Ok. Strange conclusion.

**Pull request closed without merging**
